import type { StatDefinition } from "./types";

export const defenseStats: StatDefinition[] = [
  {
    id: "sacks",
    name: "Sacks",
    category: "defense",
    summary: "The number of times a defender tackled the quarterback behind the line of scrimmage before he could throw or hand off.",
    formulaTex: "\\text{Sacks} = \\text{Full Sacks} + 0.5 \\times \\text{Shared Sacks}",
    howToRead: [
      "10+ sacks in a season is a very good pass-rushing year for an edge rusher or interior lineman; 15+ is elite, MVP-caliber production.",
      "When two defenders bring the quarterback down together, the sack is split — each gets credit for half a sack, which is why you'll see totals like 8.5 or 11.5 instead of only whole numbers.",
    ],
    pitfalls: [
      "Sacks are a 'finishing' stat — a defender who consistently pressures the quarterback into bad throws but doesn't get the sack himself won't show up here. QB hits and pressure rate (not stored in this app) fill that gap.",
      "Sack totals are pushed around a lot by scheme (how often a team blitzes, how often it rushes only 3–4) and by opposing offensive line quality, not just individual talent.",
    ],
    compute: (s) => ({
      value: s.defSacks,
      steps: [`Sacks this season (whole + half-sacks from shared sacks): ${s.defSacks}`],
    }),
    format: "decimal1",
    higherIsBetter: true,
    related: ["qb-hits", "tackles-for-loss", "epa-per-dropback"],
    availability: "1999–today",
    workedExampleSubject: "EDGE",
    qualifiedMinimum: 8,
  },
  {
    id: "qb-hits",
    name: "QB Hits",
    category: "defense",
    summary: "The number of times a defender hit the quarterback as he threw or just after, without necessarily bringing him down for a sack.",
    howToRead: [
      "QB hits capture pass-rush pressure that sacks miss entirely — a good pass rusher's QB-hit total is often much higher than his sack total, since most pressures don't end in a sack.",
      "20+ QB hits in a season is a strong, disruptive pass-rushing workload for an edge defender.",
    ],
    pitfalls: [
      "QB hits are charted by human scorers watching the broadcast, which introduces some inconsistency game to game and season to season compared to a purely objective stat.",
    ],
    compute: (s) => ({
      value: s.defQbHits,
      steps: [`QB hits this season: ${s.defQbHits}`],
    }),
    format: "int",
    higherIsBetter: true,
    related: ["sacks", "tackles-for-loss"],
    availability: "1999–today",
    workedExampleSubject: "EDGE",
    qualifiedMinimum: 8,
  },
  {
    id: "tackles-for-loss",
    name: "Tackles for Loss",
    abbr: "TFL",
    category: "defense",
    summary: "Tackles made behind the line of scrimmage — stopping a run or a screen pass before it gains positive yardage.",
    howToRead: [
      "10+ tackles for loss in a season is strong disruption from the front seven; sack totals are included here too, since a sack is also, by definition, a tackle for loss.",
      "TFLs are a good sign of a defender consistently beating his block or diagnosing plays quickly, whether he's rushing the passer or reading a run.",
    ],
    pitfalls: [
      "Like sacks, TFLs can be split between two defenders on the same play, which is why this app stores them as a real number (e.g. 7.5) rather than a whole integer.",
    ],
    compute: (s) => ({
      value: s.defTacklesForLoss,
      steps: [`Tackles for loss this season: ${s.defTacklesForLoss}`],
    }),
    format: "decimal1",
    higherIsBetter: true,
    related: ["sacks", "solo-vs-assisted-tackles"],
    availability: "1999–today",
    workedExampleSubject: "EDGE",
    qualifiedMinimum: 8,
  },
  {
    id: "solo-vs-assisted-tackles",
    name: "Solo vs. Assisted Tackles",
    category: "defense",
    summary: "A solo tackle means one defender brought the ball carrier down alone; an assisted tackle means two or more defenders share credit for the same stop.",
    formulaTex: "\\text{Total Tackles} = \\text{Solo} + \\text{Assisted}",
    howToRead: [
      "Solo tackles are the more meaningful half of the split — a defender who racks up mostly solo tackles is reliably finishing plays himself, rather than arriving after a teammate already has the ball carrier wrapped up.",
      "'Total tackles' as a single number is common in broadcasts, but always ask whether it's mostly solo or mostly assisted before judging a defender's individual impact.",
    ],
    pitfalls: [
      "Tackle totals (solo and assisted alike) are NOT an official NFL statistic — they're compiled independently by each team's own stat crew and by media outlets, which don't always agree with each other. Treat exact tackle counts as approximate, especially historically.",
      "A high tackle count can mean a defender is making a lot of plays, or it can mean his defense is on the field constantly and giving up a lot of yardage before the tackle — always check team context.",
    ],
    compute: (s) => ({
      value: s.defTacklesSolo + s.defTackleAssists,
      steps: [
        `Solo tackles: ${s.defTacklesSolo}`,
        `Assisted tackles: ${s.defTackleAssists}`,
        `${s.defTacklesSolo} + ${s.defTackleAssists} = ${s.defTacklesSolo + s.defTackleAssists} total tackles`,
      ],
    }),
    format: "int",
    higherIsBetter: true,
    related: ["tackles-for-loss"],
    availability: "1999–today",
    workedExampleSubject: "EDGE",
    qualifiedMinimum: 8,
  },
  {
    id: "def-interceptions",
    name: "Interceptions (Defense)",
    abbr: "INT",
    category: "defense",
    summary: "The number of passes a defender caught before the intended receiver could — taking the ball away through the air.",
    howToRead: [
      "4+ interceptions in a season is a strong, standout year for a cornerback or safety; 6+ is an elite, often All-Pro-caliber season.",
      "Interceptions depend partly on how often quarterbacks throw a defender's way and how often the ball simply bounces his way off a deflection — they're a noisier, less repeatable stat year to year than tackles or coverage grades.",
    ],
    pitfalls: [
      "A shutdown cornerback who's rarely thrown at all season can have very few interception chances despite excellent coverage — low INT totals don't necessarily mean poor play.",
    ],
    compute: (s) => ({
      value: s.defInterceptions,
      steps: [`Interceptions this season: ${s.defInterceptions}`],
    }),
    format: "int",
    higherIsBetter: true,
    related: ["passes-defended", "forced-fumbles"],
    availability: "1999–today",
    workedExampleSubject: "EDGE",
    qualifiedMinimum: 8,
  },
  {
    id: "passes-defended",
    name: "Passes Defended",
    abbr: "PD",
    category: "defense",
    summary: "The number of pass attempts a defender broke up or knocked down — includes interceptions plus incompletions he caused directly.",
    howToRead: [
      "Passes defended is a broader, more stable measure of coverage ability than interceptions alone, since it captures every pass a defender disrupted, not just the ones he happened to catch.",
      "10+ passes defended in a season (combined with a handful of interceptions) marks a very good coverage season for a cornerback.",
    ],
    pitfalls: [
      "This app's total combines interceptions and pass breakups into a single 'passes defended' figure as reported by the official stat feed — if a source separates the two, always check which version you're looking at.",
    ],
    compute: (s) => ({
      value: s.defPassDefended,
      steps: [`Passes defended this season: ${s.defPassDefended}`],
    }),
    format: "int",
    higherIsBetter: true,
    related: ["def-interceptions"],
    availability: "1999–today",
    workedExampleSubject: "EDGE",
    qualifiedMinimum: 8,
  },
  {
    id: "forced-fumbles",
    name: "Forced Fumbles",
    abbr: "FF",
    category: "defense",
    summary: "The number of times a defender knocked the ball loose from a ball carrier, whether or not his own team recovered it.",
    howToRead: [
      "2–3 forced fumbles in a season from a defensive lineman or linebacker is a solid, disruptive total; elite ball-hawking pass rushers can reach 4–5.",
      "A forced fumble is credited to the defender who knocked the ball out, separate from who recovers it — a teammate (or even the offense) can end up with the ball.",
    ],
    pitfalls: [
      "Whether a forced fumble is recovered by the defense is largely luck-driven (fumble recovery rate is close to 50/50 league-wide), so 'takeaways created' can look inconsistent year to year even for a player who forces fumbles at a stable rate.",
    ],
    compute: (s) => ({
      value: s.defFumblesForced,
      steps: [`Forced fumbles this season: ${s.defFumblesForced}`],
    }),
    format: "int",
    higherIsBetter: true,
    related: ["def-interceptions", "turnover-differential"],
    availability: "1999–today",
    workedExampleSubject: "EDGE",
    qualifiedMinimum: 8,
  },
];
